In [1]:
import numpy as np

In [2]:
arr_data = np.array([1,2,3,4,5,6,7,8,9])
type(arr_data)

numpy.ndarray

In [3]:
print(arr_data)

[1 2 3 4 5 6 7 8 9]


In [4]:
arr_data.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
arr = np.random.randint(0, 10, size=(3, 3))
arr

array([[4, 8, 2],
       [9, 1, 1],
       [2, 6, 3]], dtype=int32)

In [9]:
arr*3

array([[12, 24,  6],
       [27,  3,  3],
       [ 6, 18,  9]], dtype=int32)

In [17]:
list1 = [1,2,3,4,5]
arr1 = np.array(list1)
arr2 = np.random.randint(5, 10, size=(5, 1))
arr1
arr2

array([[5],
       [8],
       [8],
       [5],
       [7]], dtype=int32)

In [19]:
multiplication = arr1 * arr2
print(multiplication)

[[ 5 10 15 20 25]
 [ 8 16 24 32 40]
 [ 8 16 24 32 40]
 [ 5 10 15 20 25]
 [ 7 14 21 28 35]]
